// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDChs15hAEWnvQG0pF-SX_PSwv2qlQU-nA',
    appId: '1:104215054997:web:c4d8a8c1812153d306299c',
    messagingSenderId: '104215054997',
    projectId: 'lifespark-3a741',
    authDomain: 'lifespark-3a741.firebaseapp.com',
    storageBucket: 'lifespark-3a741.appspot.com',
    measurementId: 'G-1H7WTW3RJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqxnRqwFsi2OX_xhQ9c_LTWhrtj89wJP0',
    appId: '1:104215054997:android:19f7f6ba1284976d06299c',
    messagingSenderId: '104215054997',
    projectId: 'lifespark-3a741',
    storageBucket: 'lifespark-3a741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNg3uv-7KHQGo3oPltrBKaZG946LaQLw8',
    appId: '1:104215054997:ios:3bfdfe244cd8b10706299c',
    messagingSenderId: '104215054997',
    projectId: 'lifespark-3a741',
    storageBucket: 'lifespark-3a741.appspot.com',
    iosBundleId: 'com.example.ls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNg3uv-7KHQGo3oPltrBKaZG946LaQLw8',
    appId: '1:104215054997:ios:3bfdfe244cd8b10706299c',
    messagingSenderId: '104215054997',
    projectId: 'lifespark-3a741',
    storageBucket: 'lifespark-3a741.appspot.com',
    iosBundleId: 'com.example.ls',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDChs15hAEWnvQG0pF-SX_PSwv2qlQU-nA',
    appId: '1:104215054997:web:c7a754e73e27141a06299c',
    messagingSenderId: '104215054997',
    projectId: 'lifespark-3a741',
    authDomain: 'lifespark-3a741.firebaseapp.com',
    storageBucket: 'lifespark-3a741.appspot.com',
    measurementId: 'G-M47H3WLFR2',
  );
}
